export var ActionTypes = {
  ADD_CANDIDATE: 'ADD_CANDIDATE',
  ADD_ALL_CANDIDATES: 'ADD_ALL_CANDIDATES',

  ADD_APPLICATION: 'ADD_APPLICATION',
  ADD_ALL_APPLICATIONS: 'ADD_ALL_APPLICATIONS',

  ADD_ALL_VACANCIES: 'ADD_ALL_VACANCIES',
}
